### ISSUE TITLE
Not syncing folder changes

### ISSUE THREAD

**Issue by DarrenVs** [BrinkerVII/sync-apparatus#1]
## Priority
`Critical`

## Description
> After renaming a folder with content in windows explorer, it creates an empty folder in studio with nothing inside it until I press the "Refresh project" button.
> This process also leaves a copy/ghost of the folder I renamed with the original name in studio.
> Deleting a folder also leaves a copy/ghost of the folder in studio.

## Step by step:
1. Create a folder
2. Put a file inside it with content
3. Rename the folder that's holding the content
4. Look in studio and notice two folders in studio, one with the original name and containing the file you created, and one empty one with the renamed name

**Comment by BrinkerVII** [comment]
Issue acknowledged and fixed.

[ea3c4bd](https://github.com/BrinkerVII/sync-apparatus/commit/8be4d92f4d390a5df66654d419b1121938768771)
